"""esquema inicial

Revision ID: 5bfcffd17e46
Revises: 
Create Date: 2026-06-03 22:18:45.357520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores de la revisión, usados por Alembic.
revision: str = '5bfcffd17e46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('programa', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_codigo'), 'cursos', ['codigo'], unique=True)
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_index(op.f('ix_cursos_programa'), 'cursos', ['programa'], unique=False)
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('departamento', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesores_id'), 'profesores', ['id'], unique=False)
    op.create_index(op.f('ix_profesores_nombre'), 'profesores', ['nombre'], unique=False)
    op.create_table('curso_prerrequisito',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('prerrequisito_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerrequisito_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curso_id', 'prerrequisito_id')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('semestre_academico', sa.String(length=10), nullable=False),
    sa.Column('cupos_totales', sa.Integer(), nullable=False),
    sa.Column('cupos_disponibles', sa.Integer(), nullable=False),
    sa.Column('horario', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aula', sa.String(length=50), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_curso_id'), 'grupos', ['curso_id'], unique=False)
    op.create_index(op.f('ix_grupos_id'), 'grupos', ['id'], unique=False)
    op.create_index(op.f('ix_grupos_profesor_id'), 'grupos', ['profesor_id'], unique=False)
    op.create_index(op.f('ix_grupos_semestre_academico'), 'grupos', ['semestre_academico'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de esta migración."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grupos_semestre_academico'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_profesor_id'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_id'), table_name='grupos')
    op.drop_index(op.f('ix_grupos_curso_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_table('curso_prerrequisito')
    op.drop_index(op.f('ix_profesores_nombre'), table_name='profesores')
    op.drop_index(op.f('ix_profesores_id'), table_name='profesores')
    op.drop_table('profesores')
    op.drop_index(op.f('ix_cursos_programa'), table_name='cursos')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_index(op.f('ix_cursos_codigo'), table_name='cursos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
